title: S.M Ahsanuzzaman
logo: /assets/img/headshot_circle.jpg
description: I have a versatile IT background focused on backend development, microservices architecture, and DevOps. Specializing in optimizing systems, scalable architectures, cloud migration, CI/CD, automation, and project management in dynamic IT environments. Recognized for analytical skills and problem-solving in fast-paced, data-intensive settings. Passionate about innovation and eager to collaborate on impactful projects as a dedicated technology enthusiast.
show_downloads: true
theme: jekyll-theme-minimal
